[package]
name = "png_ect"
version = "1.0.1"
edition = "2021"
description = "A command-line tool for compressing png images using ECT."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.4.0"
rayon = "1.8.0"